Just call the function with y_true, and y_pred as input parameters, eg: 
```python
precision_score(y_true = y_true, y_pred = y_pred)
```

In [1]:
### Classification metrics

In [3]:
from metrics.classification import accuracy_score, precision_score, recall_score, f1_score
import numpy as np

In [5]:
y_true = np.random.randint(2, size = 10) # true labels (based on the dataset)
y_pred = np.random.randint(2, size = 10) # predicted labels (based on the model predictions)
y_true, y_pred

(array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1], dtype=int32),
 array([1, 1, 1, 1, 0, 1, 0, 1, 1, 1], dtype=int32))

In [7]:
accuracy_score(y_true = y_true, y_pred = y_pred)

np.float64(0.1)

In [8]:
precision_score(y_true = y_true, y_pred = y_pred, average = 'binary')

np.float64(0.125)

In [9]:
recall_score(y_true = y_true, y_pred = y_pred, average = 'binary')

np.float64(0.3333333333333333)

In [10]:
### Regression metrics

In [11]:
from metrics.regression import mean_squared_error, root_mean_squared_error, mean_absolute_error, r2_score

In [12]:
y_true = np.random.rand(10) * 100 # true values (based on the dataset)
y_pred = np.random.rand(10) * 100 # predicted values (based on the model predictions)
y_true, y_pred

(array([83.68192199, 82.85427541, 55.33645526, 76.27572523, 28.57300113,
         8.17248688, 88.98247284, 85.71661499, 58.13291785, 61.90821108]),
 array([47.3511967 , 14.87362104, 48.19005486, 49.40975173, 49.71238604,
        75.91999762, 50.27257726, 58.40787922, 34.61679486, 65.8524438 ]))

In [13]:
mean_squared_error(y_true = y_true, y_pred = y_pred)

np.float64(1456.3529421428243)

In [14]:
root_mean_squared_error(y_true = y_true, y_pred = y_pred)

np.float64(38.162192575149874)

In [16]:
mean_absolute_error(y_true = y_true, y_pred = y_pred)

np.float64(32.068963626509856)

In [17]:
r2_score(y_true = y_true, y_pred = y_pred)

np.float64(-1.2529571327089069)